# Generated by Django 3.0.6 on 2020-05-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
