# Generated by Django 3.0.6 on 2020-05-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='type',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
