# Generated by Django 3.0.6 on 2020-05-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_dinner_platters_pasta_salads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner_platters',
            old_name='price',
            new_name='price_l',
        ),
        migrations.RemoveField(
            model_name='dinner_platters',
            name='type',
        ),
        migrations.AddField(
            model_name='dinner_platters',
            name='price_m',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
