# Generated by Django 3.0.6 on 2020-05-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200518_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs',
            old_name='price',
            new_name='price_l',
        ),
        migrations.RenameField(
            model_name='subs',
            old_name='type',
            new_name='price_m',
        ),
    ]
