# Generated by Django 3.0.6 on 2020-05-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
