# Generated by Django 3.0.6 on 2020-05-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200519_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cart_detail',
            field=models.TextField(max_length=250),
        ),
    ]
