# Generated by Django 3.0.6 on 2020-05-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200519_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
